// ecosystem.config.js
module.exports = {
  apps: [
    {
      name: "auth-service",
      script: "./apps/services/auth-service/src/index.js",
      cwd: "/app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: {
        NODE_ENV: "production",
        PORT: 4001,
        MONGO_URI: process.env.MONGO_URI,
        JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        LOG_LEVEL: process.env.LOG_LEVEL || "info",
      },
      error_file: "/var/log/pm2/auth-error.log",
      out_file: "/var/log/pm2/auth-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "resume-service",
      script: "./apps/services/resume-service/src/index.js",
      cwd: "/app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: {
        NODE_ENV: "production",
        PORT: 4002,
        MONGO_URI: process.env.MONGO_URI,
        JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        LOG_LEVEL: process.env.LOG_LEVEL || "info",
      },
      error_file: "/var/log/pm2/resume-error.log",
      out_file: "/var/log/pm2/resume-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "ai-service",
      script: "./apps/services/ai-service/src/index.js",
      cwd: "/app",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "600M",
      env: {
        NODE_ENV: "production",
        PORT: 4003,
        MONGO_URI: process.env.MONGO_URI,
        OPENAI_API_KEY: process.env.OPENAI_API_KEY,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        LOG_LEVEL: process.env.LOG_LEVEL || "info",
      },
      error_file: "/var/log/pm2/ai-error.log",
      out_file: "/var/log/pm2/ai-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
  ],
};
