services:
  - type: web
    name: elevra-backend
    env: docker
    dockerfilePath: ./infra/nginx/Dockerfile
    plan: free
    autoDeploy: true
    dockerContext: ./infra/nginx
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_SERVICE_HOST
        fromService:
          type: pserv
          name: auth-service
          property: host
      - key: RESUME_SERVICE_HOST
        fromService:
          type: pserv
          name: resume-service
          property: host
      - key: AI_SERVICE_HOST
        fromService:
          type: pserv
          name: ai-service
          property: host

  # ==========================================================
  # AUTH Service
  # ==========================================================
  - type: pserv
    name: auth-service
    env: docker
    dockerfilePath: ./apps/services/auth-service/Dockerfile
    dockerContext: ./apps/services/auth-service
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4001

  # ==========================================================
  # RESUME Service
  # ==========================================================
  - type: pserv
    name: resume-service
    env: docker
    dockerfilePath: ./apps/services/resume-service/Dockerfile
    dockerContext: ./apps/services/resume-service
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4002

  # ==========================================================
  # AI Service
  # ==========================================================
  - type: pserv
    name: ai-service
    env: docker
    dockerfilePath: ./apps/services/ai-service/Dockerfile
    dockerContext: ./apps/services/ai-service
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4003
