# ------------------------------------------
# NEXT.JS DEV IMAGE (with Turbo support)
# ------------------------------------------
FROM node:20-alpine

# Workdir at monorepo root (important for Turbo)
WORKDIR /app

# Install OS deps
RUN apk add --no-cache libc6-compat

# Install Turbo globally (dev convenience)
RUN npm install -g turbo

# Copy monorepo root package.json + lockfile
COPY package.json package-lock.json turbo.json ./

COPY apps/frontend/package.json ./apps/frontend/

COPY packages/**/package.json ./packages/

# Install dependencies ONCE
RUN npm install


COPY packages ./packages

# Copy frontend source structure
COPY apps/frontend ./apps/frontend

EXPOSE 3000

# Run Next.js dev server through Turbo filter
CMD ["npm" , "run" , "dev:frontend"]
